# project: ThermoMPNN_v2
# name: EXP2.6.single.rebatched

version: v2 # options: (v1, v2, siamese)

# dataset: megascale-pt # options: (megascale, fireprot (v1 only))
dataset: megascale-test  # for arbitrary batching process
# dataset: ssym-inv

data:
  # mut_types: [single]
  mut_types: [double]
  # mut_types: [double, double-aug]

training:
  num_workers: 24
  learn_rate: 0.0001
  epochs: 50
  lr_schedule: true
  batch_size: 10000

model:
  hidden_dims: [64, 32]
  subtract_mut: true
  mutant_embedding: false
  single_target: false
  num_final_layers: 2
  freeze_weights: true
  load_pretrained: true
  lightattn: true
