# project: ThermoMPNN_v2
# name: EXP2.8.base.eps0.1

version: v2 # options: (v1, v2, siamese)

dataset: megascale-test
# dataset: fireprot-homologue-free
# dataset: ssym-dir
# dataset: ssym-inv

data:
  mut_types: [single]
  side_chains: true
  side_chain_rbfs: 16
  side_chain_topk: 30
  side_chain_augment_eps: 0.0
  thru: true

training:
  num_workers: 16
  learn_rate: 0.0001
  epochs: 100
  lr_schedule: true
  batch_size: 10000

model:
  hidden_dims: [64, 32]
  subtract_mut: true
  mutant_embedding: false
  single_target: false
  num_final_layers: 2
  freeze_weights: true
  load_pretrained: true
  lightattn: true