# project: ThermoMPNN_v2
# name: EXP2.6.drm.aug.dist

version: v2 # options: (v1, v2, siamese)

# dataset: ptmul  # for arbitrary batching capability
dataset: megascale-test
data:
  mut_types: [double]
  # mut_types: [single]
  # mut_types: [double, higher]

training:
  num_workers: 16
  learn_rate: 0.0001
  epochs: 100
  lr_schedule: true
  batch_size: 10000

model:
  hidden_dims: [64, 32]
  subtract_mut: false
  mutant_embedding: true
  single_target: true
  num_final_layers: 2
  freeze_weights: true
  load_pretrained: true
  lightattn: true
  aggregation: max
  # separate_heads: true