# project: ThermoMPNN_v2
# name: EXP2.8.drop0p1

version: v2 # options: (v1, v2, siamese)

data:
  dataset: ptmul
  splits: [alt]
  mut_types: [double, higher]
  side_chains: false

training:
  num_workers: 12
  learn_rate: 0.0001
  epochs: 100
  lr_schedule: true
  batch_size: 1
  shuffle: True

model:
  hidden_dims: [64, 32]
  subtract_mut: false
  single_target: true
  mutant_embedding: true
  num_final_layers: 2
  freeze_weights: true
  load_pretrained: true
  lightattn: true
  aggregation: max
  dropout: 0.2