platform:
  accel: "gpu"
  cache_dir: "/proj/kuhl_lab/users/dieckhau/cache"
  thermompnn_dir: "/proj/kuhl_lab/users/dieckhau/ThermoMPNN"

data_loc:
        megascale_csv: "/proj/kuhl_lab/users/dieckhau/ThermoMPNN/data/mega_scale/Processed_K50_dG_datasets/Tsuboyama2023_Dataset2_Dataset3_20230416.csv"
        megascale_splits: "/proj/kuhl_lab/users/dieckhau/ThermoMPNN/data/mega_scale/mega_splits.pkl"
        megascale_pdbs: "/proj/kuhl_lab/users/dieckhau/ThermoMPNN/data/mega_scale/AlphaFold_model_PDBs/"

        fireprot_csv: "/proj/kuhl_lab/users/dieckhau/ThermoMPNN/data/fireprot/4_fireprotDB_bestpH.csv"
        fireprot_splits: "/proj/kuhl_lab/users/dieckhau/ThermoMPNN/data/fireprot/fireprot_splits.pkl"
        fireprot_pdbs: "/proj/kuhl_lab/users/dieckhau/ThermoMPNN/data/fireprot/pdbs/monomers/"
