project: ThermoMPNN_v2
name: baselineLR

version: v2 # options: (v1, v2, siamese)

dataset: megascale # options: (megascale, fireprot (v1 only))
data:
  mut_types: [single] # options: [single, reverse, permutations]
  permissive_pdb: False  # enable permissive filename matching (useful for AF2 model checks)
  alternate_pdb: False  # enable alternate PDB filenaming (used in structure studies)

training:
  num_workers: 12
  learn_rate: 0.0001
  epochs: 100
  lr_schedule: true
  batch_size: 10000

model:
  hidden_dims: [64, 32]
  subtract_mut: true
  num_final_layers: 2
  freeze_weights: true
  load_pretrained: true
  lightattn: true
  final_layer: true

