# project: ThermoMPNN_v2
# name: AB.SE.RANGE1

version: v2

data:
  # dataset: megascale
  splits: [train_ptmul, val]
  mut_types: [double, double-aug]
  range: 3
  seed: 111
  # dataset: ptmul
  # splits: [alt]
  # mut_types: [double]

training:
  num_workers: 12
  learn_rate: 0.00001
  epochs: 100
  lr_schedule: true
  batch_size: 1 # 256
  shuffle: true

model:
  hidden_dims: [128, 128]
  subtract_mut: false
  mutant_embedding: true
  single_target: true
  num_final_layers: 2
  freeze_weights: true
  load_pretrained: true
  lightattn: true
  aggregation: siamese
  proteinmpnn_dropout: 0.0
  alpha: 1.0
  beta: 1.0
  edges: true
  dropout: 0.1
