# project: ThermoMPNN_v2
# name: single

data:
  dataset: megascale
  mut_types: [single]
  splits: [train, val]

training:
  num_workers: 24
  learn_rate: 0.00001
  epochs: 100
  lr_schedule: true
  batch_size: 256
  shuffle: true

model:
  hidden_dims: [64, 32]
  subtract_mut: true
  mutant_embedding: false
  single_target: false
  num_final_layers: 2
  freeze_weights: true
  load_pretrained: true
  lightattn: true
  proteinmpnn_dropout: 0.0
