# project: ThermoMPNN_v2
# name: EXP2.6.ME.drm

version: v2 # options: (v1, v2, siamese)

data:
  # dataset: megascale
  # mut_types: [double]
  # splits: [denovo]
  # splits: [test_cdna]
  # splits: [train_ptmul]
  # dataset: ptmul
  # mut_types: [double]
  # splits: [alt]
  dataset: proteingym
  mut_types: [double]

  # splits: [GFP_AEQVI]
  # splits: [D7PM05_CLYGR]
  # splits: [Q6WV12_9MAXI]
  # splits: [Q8WTC7_9CNID]

  splits: [HIS7_YEAST]
  # splits: [PHOT_CHLRE]

  # splits: [RASK_HUMAN]
  # pick: 1


training:
  num_workers: 12
  learn_rate: 0.00001
  epochs: 100
  lr_schedule: true
  batch_size: 1
  shuffle: false

# model:
  # hidden_dims: [64, 32]
  # subtract_mut: true
  # mutant_embedding: false
  # single_target: false
  # num_final_layers: 2
  # freeze_weights: true
  # load_pretrained: true
  # lightattn: true
  # proteinmpnn_dropout: 0.0

model:
  hidden_dims: [128, 128]
  subtract_mut: false
  mutant_embedding: true
  single_target: true
  num_final_layers: 2
  freeze_weights: true
  load_pretrained: true
  lightattn: true
  aggregation: siamese
  proteinmpnn_dropout: 0.0
  alpha: 1.0
  beta: 1.0
  edges: true
  dropout: 0.1
